GET http://localhost:3000/checkout

###
POST http://localhost:3000/checkout
Content-Type: application/json

{
    "name": "Ved",
    "email": "ved@dev.com",
    "phone": 818118181,
    "order": [{"type": "clothes"}]
}

###
POST localhost:3000/login
Content-Type: application/json

{
    "email": "jaggu@arai.com",
    "password": "12234567890"
}